input {
  file {
    path => "/path/worldcitiespop.csv"
    start_position => beginning
  }
}

filter {
  csv {
    columns => ["country","city","accentCity","region","population"]
  }

  mutate {
    add_field => { "location" => "%{column6},%{column7}" }

    remove_field => [
      "message",
      "@version",
      "@timestamp",
      "host",
      "path",
      "column6",
      "column7"
    ]
  }
}

output {
  stdout { }

  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "ciudades"
  }
}
